# Model Pipeline

Run Bayesian models across different input scalings and compare DIC.

**Output structure:** `data/models/{csv_stem}/{version}/`

In [1]:
import sys
sys.path.insert(0, '.')

import pandas as pd
from pyjags_pipeline import run_model, compare_dic, list_models

# Available input scalings
DATA_PATHS = {
    'per10k':             'data/wide_weekly_scaledPer10k.csv',
    'per-bed':            'data/wide_weekly_scaledPerBed.csv',
    'per-budget':         'data/wide_weekly_scaledPerBudgetThousands.csv',
    'budget-per-capita':  'data/wide_weekly_scaledPerBudgetBillionsPer10k.csv',
}

print('Available models:', list_models())

Available models: ['v0.1', 'v0.2', 'v1.1', 'v1.2', 'v1.3', 'v1.4', 'v1.5', 'v2.1', 'v2.2', 'v2.3', 'v3.1', 'v4.1']

## Run a single model at a single scaling

In [ ]:
result = run_model(
    version='v4.1',
    data_path=DATA_PATHS['per10k'],
    seed=42,
)

print('DIC:', result.dic)
print('Output:', result.output_dir)

[v4.1] Fitting V3.1 + Partial Pooling...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 19184 of 40000, elapsed 0:00:09, remaining 0:00:10
sampling: iterations 40000 of 40000, elapsed 0:00:14, remaining 0:00:00

## Run all models — individual scalings

In [6]:
for version in list_models():
    run_model(version=version, data_path=DATA_PATHS['per10k'], seed=42)

[v0.1] Fitting AR(1) Only...
adapting: iterations 4000 of 4000, elapsed 0:00:00, remaining 0:00:00
sampling: iterations 40000 of 40000, elapsed 0:00:04, remaining 0:00:00
sampling: iterations 26782 of 80000, elapsed 0:00:05, remaining 0:00:10
sampling: iterations 80000 of 80000, elapsed 0:00:08, remaining 0:00:00
[v0.1] Computing DIC...
updating: iterations 55672 of 80000, elapsed 0:00:08, remaining 0:00:03
updating: iterations 80000 of 80000, elapsed 0:00:08, remaining 0:00:00
[v0.1] Computing Gelman-Rubin...
[v0.1] Extracting mu, fitted, and residuals from posterior...
[v0.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.1
[v0.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.1/plots
[v0.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.1
[v0.1] Done.
[v0.2] Fitting V0.1 + AR(2)...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 31652 of 40000, elapsed 0:00:07, remaining 0:00:02
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 24344 of 80000, elapsed 0:00:07, remaining 0:00:17
sampling: iterations 69240 of 80000, elapsed 0:00:16, remaining 0:00:02
sampling: iterations 80000 of 80000, elapsed 0:00:16, remaining 0:00:00
[v0.2] Computing DIC...
updating: iterations 26078 of 80000, elapsed 0:00:07, remaining 0:00:15
updating: iterations 63888 of 80000, elapsed 0:00:13, remaining 0:00:03
updating: iterations 80000 of 80000, elapsed 0:00:15, remaining 0:00:00
[v0.2] Computing Gelman-Rubin...
[v0.2] Extracting mu, fitted, and residuals from posterior...
[v0.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.2
[v0.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.2/plots
[v0.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.2
[v0.2] Done.
[v1.1] Fitting V0.1 + Annual Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 34128 of 40000, elapsed 0:00:06, remaining 0:00:01
sampling: iterations 40000 of 40000, elapsed 0:00:06, remaining 0:00:00
sampling: iterations 35390 of 80000, elapsed 0:00:08, remaining 0:00:10
sampling: iterations 80000 of 80000, elapsed 0:00:13, remaining 0:00:00
[v1.1] Computing DIC...
updating: iterations 29018 of 80000, elapsed 0:00:07, remaining 0:00:13
updating: iterations 73470 of 80000, elapsed 0:00:12, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:13, remaining 0:00:00
[v1.1] Computing Gelman-Rubin...
[v1.1] Extracting mu, fitted, and residuals from posterior...
[v1.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.1
[v1.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.1/plots
[v1.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.1
[v1.1] Done.
[v1.2] Fitting V0.1 + 26-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 34870 of 40000, elapsed 0:00:06, remaining 0:00:01
sampling: iterations 40000 of 40000, elapsed 0:00:06, remaining 0:00:00
sampling: iterations 32752 of 80000, elapsed 0:00:07, remaining 0:00:10
sampling: iterations 80000 of 80000, elapsed 0:00:12, remaining 0:00:00
[v1.2] Computing DIC...
updating: iterations 39258 of 80000, elapsed 0:00:09, remaining 0:00:09
updating: iterations 80000 of 80000, elapsed 0:00:13, remaining 0:00:00
[v1.2] Computing Gelman-Rubin...
[v1.2] Extracting mu, fitted, and residuals from posterior...
[v1.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.2
[v1.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.2/plots
[v1.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.2
[v1.2] Done.
[v1.3] Fitting V0.1 + 8-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 30610 of 40000, elapsed 0:00:06, remaining 0:00:02
sampling: iterations 40000 of 40000, elapsed 0:00:06, remaining 0:00:00
sampling: iterations 38388 of 80000, elapsed 0:00:08, remaining 0:00:09
sampling: iterations 80000 of 80000, elapsed 0:00:12, remaining 0:00:00
[v1.3] Computing DIC...
updating: iterations 30706 of 80000, elapsed 0:00:05, remaining 0:00:08
updating: iterations 70454 of 80000, elapsed 0:00:12, remaining 0:00:02
updating: iterations 80000 of 80000, elapsed 0:00:12, remaining 0:00:00
[v1.3] Computing Gelman-Rubin...
[v1.3] Extracting mu, fitted, and residuals from posterior...
[v1.3] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.3
[v1.3] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.3/plots
[v1.3] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.3
[v1.3] Done.
[v1.4] Fitting V1.1 + 6-Month Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 29082 of 40000, elapsed 0:00:08, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:08, remaining 0:00:00
sampling: iterations 28182 of 80000, elapsed 0:00:08, remaining 0:00:15
sampling: iterations 51586 of 80000, elapsed 0:00:13, remaining 0:00:07
sampling: iterations 80000 of 80000, elapsed 0:00:17, remaining 0:00:00
[v1.4] Computing DIC...
updating: iterations 29860 of 80000, elapsed 0:00:09, remaining 0:00:15
updating: iterations 64040 of 80000, elapsed 0:00:14, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:18, remaining 0:00:00
[v1.4] Computing Gelman-Rubin...
[v1.4] Extracting mu, fitted, and residuals from posterior...
[v1.4] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.4
[v1.4] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.4/plots
[v1.4] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.4
[v1.4] Done.
[v1.5] Fitting V1.1 + 8-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 24166 of 40000, elapsed 0:00:08, remaining 0:00:05
sampling: iterations 40000 of 40000, elapsed 0:00:10, remaining 0:00:00
sampling: iterations 23208 of 80000, elapsed 0:00:08, remaining 0:00:20
sampling: iterations 43390 of 80000, elapsed 0:00:13, remaining 0:00:11
sampling: iterations 63566 of 80000, elapsed 0:00:18, remaining 0:00:05
sampling: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v1.5] Computing DIC...
updating: iterations 25270 of 80000, elapsed 0:00:09, remaining 0:00:19
updating: iterations 44978 of 80000, elapsed 0:00:14, remaining 0:00:11
updating: iterations 74432 of 80000, elapsed 0:00:19, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v1.5] Computing Gelman-Rubin...
[v1.5] Extracting mu, fitted, and residuals from posterior...
[v1.5] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.5
[v1.5] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.5/plots
[v1.5] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v1.5
[v1.5] Done.
[v2.1] Fitting V1.1 + Global New Year...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 26402 of 40000, elapsed 0:00:08, remaining 0:00:04
sampling: iterations 40000 of 40000, elapsed 0:00:09, remaining 0:00:00
sampling: iterations 25110 of 80000, elapsed 0:00:08, remaining 0:00:18
sampling: iterations 56286 of 80000, elapsed 0:00:14, remaining 0:00:06
sampling: iterations 77104 of 80000, elapsed 0:00:19, remaining 0:00:01
sampling: iterations 80000 of 80000, elapsed 0:00:19, remaining 0:00:00
[v2.1] Computing DIC...
updating: iterations 25152 of 80000, elapsed 0:00:09, remaining 0:00:19
updating: iterations 55330 of 80000, elapsed 0:00:14, remaining 0:00:06
updating: iterations 77532 of 80000, elapsed 0:00:19, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v2.1] Computing Gelman-Rubin...
[v2.1] Extracting mu, fitted, and residuals from posterior...
[v2.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.1
[v2.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.1/plots
[v2.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.1
[v2.1] Done.
[v2.2] Fitting V1.1 + Regional New Year...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 27010 of 40000, elapsed 0:00:08, remaining 0:00:04
sampling: iterations 40000 of 40000, elapsed 0:00:09, remaining 0:00:00
sampling: iterations 25776 of 80000, elapsed 0:00:09, remaining 0:00:18
sampling: iterations 57500 of 80000, elapsed 0:00:14, remaining 0:00:05
sampling: iterations 78730 of 80000, elapsed 0:00:19, remaining 0:00:00
sampling: iterations 80000 of 80000, elapsed 0:00:19, remaining 0:00:00
[v2.2] Computing DIC...
updating: iterations 29648 of 80000, elapsed 0:00:10, remaining 0:00:16
updating: iterations 50554 of 80000, elapsed 0:00:15, remaining 0:00:08
updating: iterations 80000 of 80000, elapsed 0:00:19, remaining 0:00:00
[v2.2] Computing Gelman-Rubin...
[v2.2] Extracting mu, fitted, and residuals from posterior...
[v2.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.2
[v2.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.2/plots
[v2.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.2
[v2.2] Done.
[v2.3] Fitting V1.1 + Mid West Reset...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 26700 of 40000, elapsed 0:00:09, remaining 0:00:04
sampling: iterations 40000 of 40000, elapsed 0:00:09, remaining 0:00:00
sampling: iterations 25614 of 80000, elapsed 0:00:09, remaining 0:00:18
sampling: iterations 66746 of 80000, elapsed 0:00:19, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:19, remaining 0:00:00
[v2.3] Computing DIC...
updating: iterations 23932 of 80000, elapsed 0:00:08, remaining 0:00:20
updating: iterations 44174 of 80000, elapsed 0:00:13, remaining 0:00:11
updating: iterations 74448 of 80000, elapsed 0:00:18, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v2.3] Computing Gelman-Rubin...
[v2.3] Extracting mu, fitted, and residuals from posterior...
[v2.3] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.3
[v2.3] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.3/plots
[v2.3] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.3
[v2.3] Done.
[v3.1] Fitting V2.2 + Mid West Reset...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 19264 of 40000, elapsed 0:00:09, remaining 0:00:09
sampling: iterations 40000 of 40000, elapsed 0:00:13, remaining 0:00:00
sampling: iterations 18894 of 80000, elapsed 0:00:09, remaining 0:00:28
sampling: iterations 33880 of 80000, elapsed 0:00:14, remaining 0:00:19
sampling: iterations 56322 of 80000, elapsed 0:00:19, remaining 0:00:08
sampling: iterations 71294 of 80000, elapsed 0:00:24, remaining 0:00:03
sampling: iterations 80000 of 80000, elapsed 0:00:27, remaining 0:00:00
[v3.1] Computing DIC...
updating: iterations 19406 of 80000, elapsed 0:00:09, remaining 0:00:28
updating: iterations 34224 of 80000, elapsed 0:00:14, remaining 0:00:19
updating: iterations 49036 of 80000, elapsed 0:00:19, remaining 0:00:12
updating: iterations 63846 of 80000, elapsed 0:00:24, remaining 0:00:06
updating: iterations 80000 of 80000, elapsed 0:00:27, remaining 0:00:00
[v3.1] Computing Gelman-Rubin...
[v3.1] Extracting mu, fitted, and residuals from posterior...
[v3.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.1
[v3.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.1/plots
[v3.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.1
[v3.1] Done.
[v4.1] Fitting V3.1 + Partial Pooling...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 18932 of 40000, elapsed 0:00:08, remaining 0:00:09
sampling: iterations 40000 of 40000, elapsed 0:00:13, remaining 0:00:00
sampling: iterations 19268 of 80000, elapsed 0:00:09, remaining 0:00:27
sampling: iterations 34418 of 80000, elapsed 0:00:14, remaining 0:00:18
sampling: iterations 49550 of 80000, elapsed 0:00:19, remaining 0:00:11
sampling: iterations 64642 of 80000, elapsed 0:00:24, remaining 0:00:06
sampling: iterations 80000 of 80000, elapsed 0:00:27, remaining 0:00:00
[v4.1] Computing DIC...
updating: iterations 18816 of 80000, elapsed 0:00:09, remaining 0:00:29
updating: iterations 33606 of 80000, elapsed 0:00:14, remaining 0:00:19
updating: iterations 55924 of 80000, elapsed 0:00:19, remaining 0:00:08
updating: iterations 75132 of 80000, elapsed 0:00:27, remaining 0:00:02
updating: iterations 80000 of 80000, elapsed 0:00:27, remaining 0:00:00
[v4.1] Computing Gelman-Rubin...
[v4.1] Extracting mu, fitted, and residuals from posterior...
[v4.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v4.1
[v4.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v4.1/plots
[v4.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v4.1
[v4.1] Done.

In [3]:
for version in list_models():
    run_model(version=version, data_path=DATA_PATHS['per-bed'], seed=42)

[v0.1] Fitting AR(1) Only...
adapting: iterations 4000 of 4000, elapsed 0:00:00, remaining 0:00:00
sampling: iterations 40000 of 40000, elapsed 0:00:04, remaining 0:00:00
sampling: iterations 42600 of 80000, elapsed 0:00:05, remaining 0:00:05
sampling: iterations 80000 of 80000, elapsed 0:00:10, remaining 0:00:00
[v0.1] Computing DIC...
updating: iterations 56470 of 80000, elapsed 0:00:08, remaining 0:00:03
updating: iterations 80000 of 80000, elapsed 0:00:09, remaining 0:00:00
[v0.1] Computing Gelman-Rubin...
[v0.1] Extracting mu, fitted, and residuals from posterior...
[v0.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.1
[v0.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.1/plots
[v0.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.1
[v0.1] Done.
[v0.2] Fitting V0.1 + AR(2)...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 28954 of 40000, elapsed 0:00:08, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:08, remaining 0:00:00
sampling: iterations 28962 of 80000, elapsed 0:00:08, remaining 0:00:15
sampling: iterations 64982 of 80000, elapsed 0:00:14, remaining 0:00:03
sampling: iterations 80000 of 80000, elapsed 0:00:17, remaining 0:00:00
[v0.2] Computing DIC...
updating: iterations 29770 of 80000, elapsed 0:00:09, remaining 0:00:15
updating: iterations 53298 of 80000, elapsed 0:00:14, remaining 0:00:07
updating: iterations 80000 of 80000, elapsed 0:00:17, remaining 0:00:00
[v0.2] Computing Gelman-Rubin...
[v0.2] Extracting mu, fitted, and residuals from posterior...
[v0.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.2
[v0.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.2/plots
[v0.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.2
[v0.2] Done.
[v1.1] Fitting V0.1 + Annual Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 30080 of 40000, elapsed 0:00:06, remaining 0:00:02
sampling: iterations 40000 of 40000, elapsed 0:00:06, remaining 0:00:00
sampling: iterations 32042 of 80000, elapsed 0:00:08, remaining 0:00:11
sampling: iterations 75182 of 80000, elapsed 0:00:13, remaining 0:00:01
sampling: iterations 80000 of 80000, elapsed 0:00:14, remaining 0:00:00
[v1.1] Computing DIC...
updating: iterations 33594 of 80000, elapsed 0:00:08, remaining 0:00:11
updating: iterations 76400 of 80000, elapsed 0:00:13, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:14, remaining 0:00:00
[v1.1] Computing Gelman-Rubin...
[v1.1] Extracting mu, fitted, and residuals from posterior...
[v1.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.1
[v1.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.1/plots
[v1.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.1
[v1.1] Done.
[v1.2] Fitting V0.1 + 26-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 32594 of 40000, elapsed 0:00:07, remaining 0:00:01
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 33416 of 80000, elapsed 0:00:08, remaining 0:00:11
sampling: iterations 62500 of 80000, elapsed 0:00:13, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:14, remaining 0:00:00
[v1.2] Computing DIC...
updating: iterations 19718 of 80000, elapsed 0:00:06, remaining 0:00:18
updating: iterations 61820 of 80000, elapsed 0:00:11, remaining 0:00:03
updating: iterations 80000 of 80000, elapsed 0:00:14, remaining 0:00:00
[v1.2] Computing Gelman-Rubin...
[v1.2] Extracting mu, fitted, and residuals from posterior...
[v1.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.2
[v1.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.2/plots
[v1.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.2
[v1.2] Done.
[v1.3] Fitting V0.1 + 8-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 30426 of 40000, elapsed 0:00:07, remaining 0:00:02
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 32456 of 80000, elapsed 0:00:08, remaining 0:00:12
sampling: iterations 60762 of 80000, elapsed 0:00:13, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:15, remaining 0:00:00
[v1.3] Computing DIC...
updating: iterations 34122 of 80000, elapsed 0:00:08, remaining 0:00:11
updating: iterations 75200 of 80000, elapsed 0:00:14, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:15, remaining 0:00:00
[v1.3] Computing Gelman-Rubin...
[v1.3] Extracting mu, fitted, and residuals from posterior...
[v1.3] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.3
[v1.3] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.3/plots
[v1.3] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.3
[v1.3] Done.
[v1.4] Fitting V1.1 + 6-Month Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 26998 of 40000, elapsed 0:00:09, remaining 0:00:04
sampling: iterations 40000 of 40000, elapsed 0:00:09, remaining 0:00:00
sampling: iterations 25642 of 80000, elapsed 0:00:09, remaining 0:00:19
sampling: iterations 55326 of 80000, elapsed 0:00:14, remaining 0:00:06
sampling: iterations 75286 of 80000, elapsed 0:00:19, remaining 0:00:01
sampling: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v1.4] Computing DIC...
updating: iterations 26184 of 80000, elapsed 0:00:09, remaining 0:00:18
updating: iterations 46728 of 80000, elapsed 0:00:14, remaining 0:00:10
updating: iterations 77476 of 80000, elapsed 0:00:19, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v1.4] Computing Gelman-Rubin...
[v1.4] Extracting mu, fitted, and residuals from posterior...
[v1.4] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.4
[v1.4] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.4/plots
[v1.4] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.4
[v1.4] Done.
[v1.5] Fitting V1.1 + 8-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 24584 of 40000, elapsed 0:00:09, remaining 0:00:06
sampling: iterations 40000 of 40000, elapsed 0:00:11, remaining 0:00:00
sampling: iterations 21108 of 80000, elapsed 0:00:08, remaining 0:00:23
sampling: iterations 39132 of 80000, elapsed 0:00:13, remaining 0:00:14
sampling: iterations 66114 of 80000, elapsed 0:00:19, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v1.5] Computing DIC...
updating: iterations 22594 of 80000, elapsed 0:00:09, remaining 0:00:23
updating: iterations 40220 of 80000, elapsed 0:00:14, remaining 0:00:14
updating: iterations 66506 of 80000, elapsed 0:00:19, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:23, remaining 0:00:00
[v1.5] Computing Gelman-Rubin...
[v1.5] Extracting mu, fitted, and residuals from posterior...
[v1.5] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.5
[v1.5] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.5/plots
[v1.5] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v1.5
[v1.5] Done.
[v2.1] Fitting V1.1 + Global New Year...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 21642 of 40000, elapsed 0:00:08, remaining 0:00:07
sampling: iterations 40000 of 40000, elapsed 0:00:11, remaining 0:00:00
sampling: iterations 21504 of 80000, elapsed 0:00:08, remaining 0:00:21
sampling: iterations 40082 of 80000, elapsed 0:00:13, remaining 0:00:13
sampling: iterations 58822 of 80000, elapsed 0:00:18, remaining 0:00:06
sampling: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.1] Computing DIC...
updating: iterations 21824 of 80000, elapsed 0:00:08, remaining 0:00:22
updating: iterations 39798 of 80000, elapsed 0:00:14, remaining 0:00:14
updating: iterations 65804 of 80000, elapsed 0:00:19, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:24, remaining 0:00:00
[v2.1] Computing Gelman-Rubin...
[v2.1] Extracting mu, fitted, and residuals from posterior...
[v2.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.1
[v2.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.1/plots
[v2.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.1
[v2.1] Done.
[v2.2] Fitting V1.1 + Regional New Year...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 25422 of 40000, elapsed 0:00:09, remaining 0:00:05
sampling: iterations 40000 of 40000, elapsed 0:00:10, remaining 0:00:00
sampling: iterations 21218 of 80000, elapsed 0:00:08, remaining 0:00:22
sampling: iterations 49128 of 80000, elapsed 0:00:13, remaining 0:00:08
sampling: iterations 67938 of 80000, elapsed 0:00:19, remaining 0:00:03
sampling: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.2] Computing DIC...
updating: iterations 23408 of 80000, elapsed 0:00:09, remaining 0:00:22
updating: iterations 59608 of 80000, elapsed 0:00:19, remaining 0:00:06
updating: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.2] Computing Gelman-Rubin...
[v2.2] Extracting mu, fitted, and residuals from posterior...
[v2.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.2
[v2.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.2/plots
[v2.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.2
[v2.2] Done.
[v2.3] Fitting V1.1 + Mid West Reset...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 24436 of 40000, elapsed 0:00:09, remaining 0:00:06
sampling: iterations 40000 of 40000, elapsed 0:00:11, remaining 0:00:00
sampling: iterations 12348 of 80000, elapsed 0:00:06, remaining 0:00:34
sampling: iterations 40046 of 80000, elapsed 0:00:15, remaining 0:00:15
sampling: iterations 56206 of 80000, elapsed 0:00:21, remaining 0:00:09
sampling: iterations 80000 of 80000, elapsed 0:00:26, remaining 0:00:00
[v2.3] Computing DIC...
updating: iterations 23082 of 80000, elapsed 0:00:09, remaining 0:00:22
updating: iterations 40706 of 80000, elapsed 0:00:14, remaining 0:00:13
updating: iterations 67040 of 80000, elapsed 0:00:19, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:23, remaining 0:00:00
[v2.3] Computing Gelman-Rubin...
[v2.3] Extracting mu, fitted, and residuals from posterior...
[v2.3] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.3
[v2.3] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.3/plots
[v2.3] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.3
[v2.3] Done.
[v3.1] Fitting V2.2 + Mid West Reset...
adapting: iterations 4000 of 4000, elapsed 0:00:02, remaining 0:00:00
sampling: iterations 17454 of 40000, elapsed 0:00:09, remaining 0:00:12
sampling: iterations 36252 of 40000, elapsed 0:00:14, remaining 0:00:01
sampling: iterations 40000 of 40000, elapsed 0:00:15, remaining 0:00:00
sampling: iterations 16960 of 80000, elapsed 0:00:09, remaining 0:00:32
sampling: iterations 36354 of 80000, elapsed 0:00:14, remaining 0:00:17
sampling: iterations 56266 of 80000, elapsed 0:00:23, remaining 0:00:10
sampling: iterations 69564 of 80000, elapsed 0:00:29, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:31, remaining 0:00:00
[v3.1] Computing DIC...
updating: iterations 16790 of 80000, elapsed 0:00:09, remaining 0:00:35
updating: iterations 42608 of 80000, elapsed 0:00:19, remaining 0:00:17
updating: iterations 55526 of 80000, elapsed 0:00:24, remaining 0:00:11
updating: iterations 76950 of 80000, elapsed 0:00:30, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:31, remaining 0:00:00
[v3.1] Computing Gelman-Rubin...
[v3.1] Extracting mu, fitted, and residuals from posterior...
[v3.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v3.1
[v3.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v3.1/plots
[v3.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v3.1
[v3.1] Done.
[v4.1] Fitting V3.1 + Partial Pooling...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 18370 of 40000, elapsed 0:00:09, remaining 0:00:10
sampling: iterations 32276 of 40000, elapsed 0:00:14, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:15, remaining 0:00:00
sampling: iterations 17098 of 80000, elapsed 0:00:09, remaining 0:00:32
sampling: iterations 30572 of 80000, elapsed 0:00:14, remaining 0:00:22
sampling: iterations 50660 of 80000, elapsed 0:00:19, remaining 0:00:11
sampling: iterations 70994 of 80000, elapsed 0:00:29, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:30, remaining 0:00:00
[v4.1] Computing DIC...
updating: iterations 16566 of 80000, elapsed 0:00:09, remaining 0:00:34
updating: iterations 36468 of 80000, elapsed 0:00:14, remaining 0:00:16
updating: iterations 42988 of 80000, elapsed 0:00:19, remaining 0:00:16
updating: iterations 62890 of 80000, elapsed 0:00:24, remaining 0:00:06
updating: iterations 77386 of 80000, elapsed 0:00:30, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:32, remaining 0:00:00
[v4.1] Computing Gelman-Rubin...
[v4.1] Extracting mu, fitted, and residuals from posterior...
[v4.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v4.1
[v4.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v4.1/plots
[v4.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v4.1
[v4.1] Done.

In [4]:
for version in list_models():
    run_model(version=version, data_path=DATA_PATHS['per-budget'], seed=42)

[v0.1] Fitting AR(1) Only...
adapting: iterations 4000 of 4000, elapsed 0:00:00, remaining 0:00:00
sampling: iterations 40000 of 40000, elapsed 0:00:04, remaining 0:00:00
sampling: iterations 45858 of 80000, elapsed 0:00:06, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:09, remaining 0:00:00
[v0.1] Computing DIC...
updating: iterations 51752 of 80000, elapsed 0:00:08, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:09, remaining 0:00:00
[v0.1] Computing Gelman-Rubin...
[v0.1] Extracting mu, fitted, and residuals from posterior...
[v0.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v0.1
[v0.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v0.1/plots
[v0.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v0.1
[v0.1] Done.
[v0.2] Fitting V0.1 + AR(2)...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 29908 of 40000, elapsed 0:00:08, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:08, remaining 0:00:00
sampling: iterations 28036 of 80000, elapsed 0:00:08, remaining 0:00:15
sampling: iterations 63950 of 80000, elapsed 0:00:13, remaining 0:00:03
sampling: iterations 80000 of 80000, elapsed 0:00:17, remaining 0:00:00
[v0.2] Computing DIC...
updating: iterations 29060 of 80000, elapsed 0:00:08, remaining 0:00:14
updating: iterations 52228 of 80000, elapsed 0:00:13, remaining 0:00:07
updating: iterations 80000 of 80000, elapsed 0:00:17, remaining 0:00:00
[v0.2] Computing Gelman-Rubin...
[v0.2] Extracting mu, fitted, and residuals from posterior...
[v0.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v0.2
[v0.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v0.2/plots
[v0.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v0.2
[v0.2] Done.
[v1.1] Fitting V0.1 + Annual Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 34300 of 40000, elapsed 0:00:07, remaining 0:00:01
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 35600 of 80000, elapsed 0:00:08, remaining 0:00:11
sampling: iterations 64232 of 80000, elapsed 0:00:14, remaining 0:00:03
sampling: iterations 80000 of 80000, elapsed 0:00:15, remaining 0:00:00
[v1.1] Computing DIC...
updating: iterations 34670 of 80000, elapsed 0:00:08, remaining 0:00:11
updating: iterations 75866 of 80000, elapsed 0:00:14, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:15, remaining 0:00:00
[v1.1] Computing Gelman-Rubin...
[v1.1] Extracting mu, fitted, and residuals from posterior...
[v1.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.1
[v1.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.1/plots
[v1.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.1
[v1.1] Done.
[v1.2] Fitting V0.1 + 26-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 33234 of 40000, elapsed 0:00:06, remaining 0:00:01
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 31668 of 80000, elapsed 0:00:08, remaining 0:00:12
sampling: iterations 60588 of 80000, elapsed 0:00:13, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:14, remaining 0:00:00
[v1.2] Computing DIC...
updating: iterations 36482 of 80000, elapsed 0:00:09, remaining 0:00:10
updating: iterations 78394 of 80000, elapsed 0:00:14, remaining 0:00:00
updating: iterations 80000 of 80000, elapsed 0:00:14, remaining 0:00:00
[v1.2] Computing Gelman-Rubin...
[v1.2] Extracting mu, fitted, and residuals from posterior...
[v1.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.2
[v1.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.2/plots
[v1.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.2
[v1.2] Done.
[v1.3] Fitting V0.1 + 8-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 32242 of 40000, elapsed 0:00:07, remaining 0:00:02
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 28240 of 80000, elapsed 0:00:07, remaining 0:00:14
sampling: iterations 68756 of 80000, elapsed 0:00:13, remaining 0:00:02
sampling: iterations 80000 of 80000, elapsed 0:00:15, remaining 0:00:00
[v1.3] Computing DIC...
updating: iterations 33806 of 80000, elapsed 0:00:08, remaining 0:00:11
updating: iterations 61528 of 80000, elapsed 0:00:13, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:15, remaining 0:00:00
[v1.3] Computing Gelman-Rubin...
[v1.3] Extracting mu, fitted, and residuals from posterior...
[v1.3] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.3
[v1.3] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.3/plots
[v1.3] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.3
[v1.3] Done.
[v1.4] Fitting V1.1 + 6-Month Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 27430 of 40000, elapsed 0:00:09, remaining 0:00:04
sampling: iterations 40000 of 40000, elapsed 0:00:10, remaining 0:00:00
sampling: iterations 24070 of 80000, elapsed 0:00:08, remaining 0:00:19
sampling: iterations 54638 of 80000, elapsed 0:00:14, remaining 0:00:06
sampling: iterations 75206 of 80000, elapsed 0:00:19, remaining 0:00:01
sampling: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v1.4] Computing DIC...
updating: iterations 25520 of 80000, elapsed 0:00:09, remaining 0:00:19
updating: iterations 56004 of 80000, elapsed 0:00:14, remaining 0:00:06
updating: iterations 76820 of 80000, elapsed 0:00:19, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v1.4] Computing Gelman-Rubin...
[v1.4] Extracting mu, fitted, and residuals from posterior...
[v1.4] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.4
[v1.4] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.4/plots
[v1.4] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.4
[v1.4] Done.
[v1.5] Fitting V1.1 + 8-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 23668 of 40000, elapsed 0:00:09, remaining 0:00:06
sampling: iterations 40000 of 40000, elapsed 0:00:11, remaining 0:00:00
sampling: iterations 22698 of 80000, elapsed 0:00:09, remaining 0:00:22
sampling: iterations 49768 of 80000, elapsed 0:00:14, remaining 0:00:09
sampling: iterations 67810 of 80000, elapsed 0:00:19, remaining 0:00:03
sampling: iterations 80000 of 80000, elapsed 0:00:23, remaining 0:00:00
[v1.5] Computing DIC...
updating: iterations 20490 of 80000, elapsed 0:00:08, remaining 0:00:24
updating: iterations 38106 of 80000, elapsed 0:00:13, remaining 0:00:15
updating: iterations 55778 of 80000, elapsed 0:00:18, remaining 0:00:08
updating: iterations 80000 of 80000, elapsed 0:00:23, remaining 0:00:00
[v1.5] Computing Gelman-Rubin...
[v1.5] Extracting mu, fitted, and residuals from posterior...
[v1.5] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.5
[v1.5] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.5/plots
[v1.5] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v1.5
[v1.5] Done.
[v2.1] Fitting V1.1 + Global New Year...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 25340 of 40000, elapsed 0:00:09, remaining 0:00:05
sampling: iterations 40000 of 40000, elapsed 0:00:10, remaining 0:00:00
sampling: iterations 23736 of 80000, elapsed 0:00:09, remaining 0:00:20
sampling: iterations 52126 of 80000, elapsed 0:00:14, remaining 0:00:07
sampling: iterations 71180 of 80000, elapsed 0:00:19, remaining 0:00:02
sampling: iterations 80000 of 80000, elapsed 0:00:21, remaining 0:00:00
[v2.1] Computing DIC...
updating: iterations 23802 of 80000, elapsed 0:00:09, remaining 0:00:21
updating: iterations 42620 of 80000, elapsed 0:00:14, remaining 0:00:12
updating: iterations 61424 of 80000, elapsed 0:00:19, remaining 0:00:06
updating: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.1] Computing Gelman-Rubin...
[v2.1] Extracting mu, fitted, and residuals from posterior...
[v2.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v2.1
[v2.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v2.1/plots
[v2.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v2.1
[v2.1] Done.
[v2.2] Fitting V1.1 + Regional New Year...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 25558 of 40000, elapsed 0:00:09, remaining 0:00:05
sampling: iterations 40000 of 40000, elapsed 0:00:10, remaining 0:00:00
sampling: iterations 23694 of 80000, elapsed 0:00:09, remaining 0:00:21
sampling: iterations 61786 of 80000, elapsed 0:00:19, remaining 0:00:06
sampling: iterations 80000 of 80000, elapsed 0:00:21, remaining 0:00:00
[v2.2] Computing DIC...
updating: iterations 23776 of 80000, elapsed 0:00:09, remaining 0:00:21
updating: iterations 50856 of 80000, elapsed 0:00:14, remaining 0:00:08
updating: iterations 69040 of 80000, elapsed 0:00:19, remaining 0:00:03
updating: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.2] Computing Gelman-Rubin...
[v2.2] Extracting mu, fitted, and residuals from posterior...
[v2.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v2.2
[v2.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v2.2/plots
[v2.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v2.2
[v2.2] Done.
[v2.3] Fitting V1.1 + Mid West Reset...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 23720 of 40000, elapsed 0:00:09, remaining 0:00:06
sampling: iterations 40000 of 40000, elapsed 0:00:11, remaining 0:00:00
sampling: iterations 23466 of 80000, elapsed 0:00:09, remaining 0:00:21
sampling: iterations 50958 of 80000, elapsed 0:00:14, remaining 0:00:08
sampling: iterations 69418 of 80000, elapsed 0:00:19, remaining 0:00:03
sampling: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.3] Computing DIC...
updating: iterations 24204 of 80000, elapsed 0:00:09, remaining 0:00:21
updating: iterations 42498 of 80000, elapsed 0:00:14, remaining 0:00:12
updating: iterations 69796 of 80000, elapsed 0:00:20, remaining 0:00:03
updating: iterations 80000 of 80000, elapsed 0:00:23, remaining 0:00:00
[v2.3] Computing Gelman-Rubin...
[v2.3] Extracting mu, fitted, and residuals from posterior...
[v2.3] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v2.3
[v2.3] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v2.3/plots
[v2.3] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v2.3
[v2.3] Done.
[v3.1] Fitting V2.2 + Mid West Reset...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 18490 of 40000, elapsed 0:00:09, remaining 0:00:11
sampling: iterations 32362 of 40000, elapsed 0:00:14, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:14, remaining 0:00:00
sampling: iterations 17388 of 80000, elapsed 0:00:09, remaining 0:00:31
sampling: iterations 31016 of 80000, elapsed 0:00:14, remaining 0:00:22
sampling: iterations 51456 of 80000, elapsed 0:00:19, remaining 0:00:11
sampling: iterations 65120 of 80000, elapsed 0:00:24, remaining 0:00:05
sampling: iterations 78770 of 80000, elapsed 0:00:29, remaining 0:00:00
sampling: iterations 80000 of 80000, elapsed 0:00:30, remaining 0:00:00
[v3.1] Computing DIC...
updating: iterations 18464 of 80000, elapsed 0:00:09, remaining 0:00:31
updating: iterations 32012 of 80000, elapsed 0:00:14, remaining 0:00:22
updating: iterations 45468 of 80000, elapsed 0:00:19, remaining 0:00:15
updating: iterations 58878 of 80000, elapsed 0:00:24, remaining 0:00:09
updating: iterations 72222 of 80000, elapsed 0:00:30, remaining 0:00:03
updating: iterations 80000 of 80000, elapsed 0:00:30, remaining 0:00:00
[v3.1] Computing Gelman-Rubin...
[v3.1] Extracting mu, fitted, and residuals from posterior...
[v3.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v3.1
[v3.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v3.1/plots
[v3.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v3.1
[v3.1] Done.
[v4.1] Fitting V3.1 + Partial Pooling...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 18244 of 40000, elapsed 0:00:09, remaining 0:00:10
sampling: iterations 39156 of 40000, elapsed 0:00:14, remaining 0:00:00
sampling: iterations 40000 of 40000, elapsed 0:00:14, remaining 0:00:00
sampling: iterations 18164 of 80000, elapsed 0:00:09, remaining 0:00:31
sampling: iterations 31770 of 80000, elapsed 0:00:14, remaining 0:00:21
sampling: iterations 52208 of 80000, elapsed 0:00:19, remaining 0:00:10
sampling: iterations 65880 of 80000, elapsed 0:00:24, remaining 0:00:05
sampling: iterations 80000 of 80000, elapsed 0:00:29, remaining 0:00:00
sampling: iterations 80000 of 80000, elapsed 0:00:29, remaining 0:00:00
[v4.1] Computing DIC...
updating: iterations 17474 of 80000, elapsed 0:00:09, remaining 0:00:32
updating: iterations 37836 of 80000, elapsed 0:00:14, remaining 0:00:16
updating: iterations 51400 of 80000, elapsed 0:00:19, remaining 0:00:11
updating: iterations 64964 of 80000, elapsed 0:00:24, remaining 0:00:06
updating: iterations 78526 of 80000, elapsed 0:00:29, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:30, remaining 0:00:00
[v4.1] Computing Gelman-Rubin...
[v4.1] Extracting mu, fitted, and residuals from posterior...
[v4.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v4.1
[v4.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v4.1/plots
[v4.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetThousands/v4.1
[v4.1] Done.

In [5]:
for version in list_models():
    run_model(version=version, data_path=DATA_PATHS['budget-per-capita'], seed=42)

[v0.1] Fitting AR(1) Only...
adapting: iterations 4000 of 4000, elapsed 0:00:00, remaining 0:00:00
sampling: iterations 40000 of 40000, elapsed 0:00:04, remaining 0:00:00
sampling: iterations 59732 of 80000, elapsed 0:00:08, remaining 0:00:03
sampling: iterations 80000 of 80000, elapsed 0:00:08, remaining 0:00:00
[v0.1] Computing DIC...
updating: iterations 53328 of 80000, elapsed 0:00:08, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:09, remaining 0:00:00
[v0.1] Computing Gelman-Rubin...
[v0.1] Extracting mu, fitted, and residuals from posterior...
[v0.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v0.1
[v0.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v0.1/plots
[v0.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v0.1
[v0.1] Done.
[v0.2] Fitting V0.1 + AR(2)...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 28280 of 40000, elapsed 0:00:08, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:08, remaining 0:00:00
sampling: iterations 24832 of 80000, elapsed 0:00:07, remaining 0:00:16
sampling: iterations 61084 of 80000, elapsed 0:00:13, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:17, remaining 0:00:00
[v0.2] Computing DIC...
updating: iterations 28734 of 80000, elapsed 0:00:08, remaining 0:00:15
updating: iterations 51920 of 80000, elapsed 0:00:13, remaining 0:00:07
updating: iterations 80000 of 80000, elapsed 0:00:17, remaining 0:00:00
[v0.2] Computing Gelman-Rubin...
[v0.2] Extracting mu, fitted, and residuals from posterior...
[v0.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v0.2
[v0.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v0.2/plots
[v0.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v0.2
[v0.2] Done.
[v1.1] Fitting V0.1 + Annual Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 30944 of 40000, elapsed 0:00:06, remaining 0:00:02
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 31640 of 80000, elapsed 0:00:08, remaining 0:00:12
sampling: iterations 59954 of 80000, elapsed 0:00:13, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:14, remaining 0:00:00
[v1.1] Computing DIC...
updating: iterations 31576 of 80000, elapsed 0:00:08, remaining 0:00:12
updating: iterations 73514 of 80000, elapsed 0:00:14, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:15, remaining 0:00:00
[v1.1] Computing Gelman-Rubin...
[v1.1] Extracting mu, fitted, and residuals from posterior...
[v1.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.1
[v1.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.1/plots
[v1.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.1
[v1.1] Done.
[v1.2] Fitting V0.1 + 26-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 33060 of 40000, elapsed 0:00:07, remaining 0:00:01
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 30692 of 80000, elapsed 0:00:08, remaining 0:00:12
sampling: iterations 72164 of 80000, elapsed 0:00:13, remaining 0:00:01
sampling: iterations 80000 of 80000, elapsed 0:00:14, remaining 0:00:00
[v1.2] Computing DIC...
updating: iterations 33788 of 80000, elapsed 0:00:08, remaining 0:00:12
updating: iterations 61492 of 80000, elapsed 0:00:14, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:15, remaining 0:00:00
[v1.2] Computing Gelman-Rubin...
[v1.2] Extracting mu, fitted, and residuals from posterior...
[v1.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.2
[v1.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.2/plots
[v1.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.2
[v1.2] Done.
[v1.3] Fitting V0.1 + 8-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 27166 of 40000, elapsed 0:00:05, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 33168 of 80000, elapsed 0:00:08, remaining 0:00:12
sampling: iterations 75612 of 80000, elapsed 0:00:13, remaining 0:00:01
sampling: iterations 80000 of 80000, elapsed 0:00:14, remaining 0:00:00
[v1.3] Computing DIC...
updating: iterations 34846 of 80000, elapsed 0:00:09, remaining 0:00:11
updating: iterations 76950 of 80000, elapsed 0:00:14, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:14, remaining 0:00:00
[v1.3] Computing Gelman-Rubin...
[v1.3] Extracting mu, fitted, and residuals from posterior...
[v1.3] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.3
[v1.3] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.3/plots
[v1.3] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.3
[v1.3] Done.
[v1.4] Fitting V1.1 + 6-Month Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 27198 of 40000, elapsed 0:00:08, remaining 0:00:04
sampling: iterations 40000 of 40000, elapsed 0:00:09, remaining 0:00:00
sampling: iterations 25024 of 80000, elapsed 0:00:09, remaining 0:00:19
sampling: iterations 45454 of 80000, elapsed 0:00:14, remaining 0:00:10
sampling: iterations 65868 of 80000, elapsed 0:00:19, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v1.4] Computing DIC...
updating: iterations 23964 of 80000, elapsed 0:00:08, remaining 0:00:19
updating: iterations 54112 of 80000, elapsed 0:00:14, remaining 0:00:07
updating: iterations 74212 of 80000, elapsed 0:00:19, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v1.4] Computing Gelman-Rubin...
[v1.4] Extracting mu, fitted, and residuals from posterior...
[v1.4] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.4
[v1.4] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.4/plots
[v1.4] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.4
[v1.4] Done.
[v1.5] Fitting V1.1 + 8-Week Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 23590 of 40000, elapsed 0:00:09, remaining 0:00:06
sampling: iterations 40000 of 40000, elapsed 0:00:11, remaining 0:00:00
sampling: iterations 21736 of 80000, elapsed 0:00:09, remaining 0:00:23
sampling: iterations 39446 of 80000, elapsed 0:00:14, remaining 0:00:14
sampling: iterations 72672 of 80000, elapsed 0:00:23, remaining 0:00:02
sampling: iterations 80000 of 80000, elapsed 0:00:23, remaining 0:00:00
[v1.5] Computing DIC...
updating: iterations 21780 of 80000, elapsed 0:00:09, remaining 0:00:23
updating: iterations 39470 of 80000, elapsed 0:00:14, remaining 0:00:14
updating: iterations 57140 of 80000, elapsed 0:00:19, remaining 0:00:07
updating: iterations 80000 of 80000, elapsed 0:00:23, remaining 0:00:00
[v1.5] Computing Gelman-Rubin...
[v1.5] Extracting mu, fitted, and residuals from posterior...
[v1.5] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.5
[v1.5] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.5/plots
[v1.5] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v1.5
[v1.5] Done.
[v2.1] Fitting V1.1 + Global New Year...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 24228 of 40000, elapsed 0:00:09, remaining 0:00:06
sampling: iterations 40000 of 40000, elapsed 0:00:10, remaining 0:00:00
sampling: iterations 23348 of 80000, elapsed 0:00:08, remaining 0:00:21
sampling: iterations 42112 of 80000, elapsed 0:00:14, remaining 0:00:12
sampling: iterations 60810 of 80000, elapsed 0:00:19, remaining 0:00:06
sampling: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.1] Computing DIC...
updating: iterations 24422 of 80000, elapsed 0:00:09, remaining 0:00:20
updating: iterations 42820 of 80000, elapsed 0:00:14, remaining 0:00:12
updating: iterations 61212 of 80000, elapsed 0:00:19, remaining 0:00:06
updating: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.1] Computing Gelman-Rubin...
[v2.1] Extracting mu, fitted, and residuals from posterior...
[v2.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v2.1
[v2.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v2.1/plots
[v2.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v2.1
[v2.1] Done.
[v2.2] Fitting V1.1 + Regional New Year...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 28208 of 40000, elapsed 0:00:10, remaining 0:00:04
sampling: iterations 40000 of 40000, elapsed 0:00:10, remaining 0:00:00
sampling: iterations 22106 of 80000, elapsed 0:00:08, remaining 0:00:22
sampling: iterations 41194 of 80000, elapsed 0:00:13, remaining 0:00:13
sampling: iterations 60182 of 80000, elapsed 0:00:18, remaining 0:00:06
sampling: iterations 80000 of 80000, elapsed 0:00:21, remaining 0:00:00
[v2.2] Computing DIC...
updating: iterations 21400 of 80000, elapsed 0:00:08, remaining 0:00:22
updating: iterations 49264 of 80000, elapsed 0:00:13, remaining 0:00:08
updating: iterations 67842 of 80000, elapsed 0:00:18, remaining 0:00:03
updating: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.2] Computing Gelman-Rubin...
[v2.2] Extracting mu, fitted, and residuals from posterior...
[v2.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v2.2
[v2.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v2.2/plots
[v2.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v2.2
[v2.2] Done.
[v2.3] Fitting V1.1 + Mid West Reset...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 24444 of 40000, elapsed 0:00:09, remaining 0:00:06
sampling: iterations 40000 of 40000, elapsed 0:00:11, remaining 0:00:00
sampling: iterations 21078 of 80000, elapsed 0:00:08, remaining 0:00:23
sampling: iterations 48170 of 80000, elapsed 0:00:13, remaining 0:00:09
sampling: iterations 66308 of 80000, elapsed 0:00:18, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.3] Computing DIC...
updating: iterations 21812 of 80000, elapsed 0:00:09, remaining 0:00:23
updating: iterations 48718 of 80000, elapsed 0:00:14, remaining 0:00:09
updating: iterations 72856 of 80000, elapsed 0:00:22, remaining 0:00:02
updating: iterations 80000 of 80000, elapsed 0:00:23, remaining 0:00:00
[v2.3] Computing Gelman-Rubin...
[v2.3] Extracting mu, fitted, and residuals from posterior...
[v2.3] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v2.3
[v2.3] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v2.3/plots
[v2.3] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v2.3
[v2.3] Done.
[v3.1] Fitting V2.2 + Mid West Reset...
adapting: iterations 4000 of 4000, elapsed 0:00:02, remaining 0:00:00
sampling: iterations 11564 of 40000, elapsed 0:00:06, remaining 0:00:16
sampling: iterations 24822 of 40000, elapsed 0:00:11, remaining 0:00:07
sampling: iterations 40000 of 40000, elapsed 0:00:15, remaining 0:00:00
sampling: iterations 16174 of 80000, elapsed 0:00:08, remaining 0:00:33
sampling: iterations 29514 of 80000, elapsed 0:00:13, remaining 0:00:23
sampling: iterations 49546 of 80000, elapsed 0:00:19, remaining 0:00:11
sampling: iterations 62876 of 80000, elapsed 0:00:24, remaining 0:00:06
sampling: iterations 76124 of 80000, elapsed 0:00:29, remaining 0:00:01
sampling: iterations 80000 of 80000, elapsed 0:00:30, remaining 0:00:00
[v3.1] Computing DIC...
updating: iterations 16946 of 80000, elapsed 0:00:09, remaining 0:00:33
updating: iterations 43304 of 80000, elapsed 0:00:19, remaining 0:00:16
updating: iterations 56482 of 80000, elapsed 0:00:24, remaining 0:00:10
updating: iterations 69624 of 80000, elapsed 0:00:29, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:31, remaining 0:00:00
[v3.1] Computing Gelman-Rubin...
[v3.1] Extracting mu, fitted, and residuals from posterior...
[v3.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v3.1
[v3.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v3.1/plots
[v3.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v3.1
[v3.1] Done.
[v4.1] Fitting V3.1 + Partial Pooling...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 17930 of 40000, elapsed 0:00:09, remaining 0:00:11
sampling: iterations 39144 of 40000, elapsed 0:00:14, remaining 0:00:00
sampling: iterations 40000 of 40000, elapsed 0:00:15, remaining 0:00:00
sampling: iterations 17068 of 80000, elapsed 0:00:09, remaining 0:00:33
sampling: iterations 30528 of 80000, elapsed 0:00:14, remaining 0:00:22
sampling: iterations 50708 of 80000, elapsed 0:00:19, remaining 0:00:11
sampling: iterations 70824 of 80000, elapsed 0:00:29, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:30, remaining 0:00:00
[v4.1] Computing DIC...
updating: iterations 16684 of 80000, elapsed 0:00:09, remaining 0:00:33
updating: iterations 36648 of 80000, elapsed 0:00:14, remaining 0:00:16
updating: iterations 56548 of 80000, elapsed 0:00:24, remaining 0:00:10
updating: iterations 76522 of 80000, elapsed 0:00:29, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:30, remaining 0:00:00
[v4.1] Computing Gelman-Rubin...
[v4.1] Extracting mu, fitted, and residuals from posterior...
[v4.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v4.1
[v4.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v4.1/plots
[v4.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBudgetBillionsPer10k/v4.1
[v4.1] Done.

## Run all models across all scalings

In [15]:
for scaling, path in DATA_PATHS.items():
    print(f'\n=== {scaling} ===')
    for version in list_models():
        run_model(version=version, data_path=path, seed=42)

=== per10k ===
[v0.1] Fitting AR(1) Only...
adapting: iterations 4000 of 4000, elapsed 0:00:00, remaining 0:00:00
sampling: iterations 40000 of 40000, elapsed 0:00:03, remaining 0:00:00
sampling: iterations 27668 of 80000, elapsed 0:00:05, remaining 0:00:10
sampling: iterations 80000 of 80000, elapsed 0:00:08, remaining 0:00:00
[v0.1] Computing DIC...
updating: iterations 64268 of 80000, elapsed 0:00:08, remaining 0:00:02
updating: iterations 80000 of 80000, elapsed 0:00:08, remaining 0:00:00
[v0.1] Computing Gelman-Rubin...
[v0.1] Extracting mu, fitted, and residuals from posterior...
[v0.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.1
[v0.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.1/plots
[v0.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.1
[v0.1] Done.
[v0.2] Fitting AR(2) Only...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 30446 of 40000, elapsed 0:00:07, remaining 0:00:02
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 36350 of 80000, elapsed 0:00:09, remaining 0:00:11
sampling: iterations 62546 of 80000, elapsed 0:00:14, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:15, remaining 0:00:00
[v0.2] Computing DIC...
updating: iterations 29438 of 80000, elapsed 0:00:08, remaining 0:00:14
updating: iterations 54332 of 80000, elapsed 0:00:13, remaining 0:00:06
updating: iterations 80000 of 80000, elapsed 0:00:16, remaining 0:00:00
[v0.2] Computing Gelman-Rubin...
[v0.2] Extracting mu, fitted, and residuals from posterior...
[v0.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.2
[v0.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.2/plots
[v0.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v0.2
[v0.2] Done.
[v2.1] Fitting AR(1) + Annual Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 35060 of 40000, elapsed 0:00:06, remaining 0:00:01
sampling: iterations 40000 of 40000, elapsed 0:00:06, remaining 0:00:00
sampling: iterations 44636 of 80000, elapsed 0:00:09, remaining 0:00:07
sampling: iterations 80000 of 80000, elapsed 0:00:13, remaining 0:00:00
[v2.1] Computing DIC...
updating: iterations 35506 of 80000, elapsed 0:00:08, remaining 0:00:10
updating: iterations 80000 of 80000, elapsed 0:00:13, remaining 0:00:00
[v2.1] Computing Gelman-Rubin...
[v2.1] Extracting mu, fitted, and residuals from posterior...
[v2.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.1
[v2.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.1/plots
[v2.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.1
[v2.1] Done.
[v2.2] Fitting 6 Month Cycle Only...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 30264 of 40000, elapsed 0:00:05, remaining 0:00:02
sampling: iterations 40000 of 40000, elapsed 0:00:06, remaining 0:00:00
sampling: iterations 41194 of 80000, elapsed 0:00:09, remaining 0:00:08
sampling: iterations 80000 of 80000, elapsed 0:00:13, remaining 0:00:00
[v2.2] Computing DIC...
updating: iterations 38056 of 80000, elapsed 0:00:09, remaining 0:00:10
updating: iterations 80000 of 80000, elapsed 0:00:13, remaining 0:00:00
[v2.2] Computing Gelman-Rubin...
[v2.2] Extracting mu, fitted, and residuals from posterior...
[v2.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.2
[v2.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.2/plots
[v2.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.2
[v2.2] Done.
[v2.3] Fitting 2 Month Cycle Only...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 36128 of 40000, elapsed 0:00:06, remaining 0:00:01
sampling: iterations 40000 of 40000, elapsed 0:00:06, remaining 0:00:00
sampling: iterations 44442 of 80000, elapsed 0:00:09, remaining 0:00:07
sampling: iterations 80000 of 80000, elapsed 0:00:12, remaining 0:00:00
[v2.3] Computing DIC...
updating: iterations 35492 of 80000, elapsed 0:00:08, remaining 0:00:10
updating: iterations 80000 of 80000, elapsed 0:00:13, remaining 0:00:00
[v2.3] Computing Gelman-Rubin...
[v2.3] Extracting mu, fitted, and residuals from posterior...
[v2.3] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.3
[v2.3] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.3/plots
[v2.3] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.3
[v2.3] Done.
[v2.4] Fitting Annual + 6-Month Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 30210 of 40000, elapsed 0:00:08, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:08, remaining 0:00:00
sampling: iterations 31202 of 80000, elapsed 0:00:09, remaining 0:00:14
sampling: iterations 65454 of 80000, elapsed 0:00:15, remaining 0:00:03
sampling: iterations 80000 of 80000, elapsed 0:00:18, remaining 0:00:00
[v2.4] Computing DIC...
updating: iterations 26068 of 80000, elapsed 0:00:09, remaining 0:00:18
updating: iterations 58236 of 80000, elapsed 0:00:14, remaining 0:00:05
updating: iterations 80000 of 80000, elapsed 0:00:19, remaining 0:00:00
updating: iterations 80000 of 80000, elapsed 0:00:19, remaining 0:00:00
[v2.4] Computing Gelman-Rubin...
[v2.4] Extracting mu, fitted, and residuals from posterior...
[v2.4] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.4
[v2.4] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.4/plots
[v2.4] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.4
[v2.4] Done.
[v2.5] Fitting Annual + 2-Month Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 29172 of 40000, elapsed 0:00:09, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:10, remaining 0:00:00
sampling: iterations 25412 of 80000, elapsed 0:00:09, remaining 0:00:19
sampling: iterations 44710 of 80000, elapsed 0:00:14, remaining 0:00:11
sampling: iterations 63720 of 80000, elapsed 0:00:20, remaining 0:00:05
sampling: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.5] Computing DIC...
updating: iterations 21656 of 80000, elapsed 0:00:08, remaining 0:00:22
updating: iterations 40682 of 80000, elapsed 0:00:13, remaining 0:00:13
updating: iterations 59610 of 80000, elapsed 0:00:19, remaining 0:00:06
updating: iterations 80000 of 80000, elapsed 0:00:22, remaining 0:00:00
[v2.5] Computing Gelman-Rubin...
[v2.5] Extracting mu, fitted, and residuals from posterior...
[v2.5] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.5
[v2.5] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.5/plots
[v2.5] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v2.5
[v2.5] Done.
[v3.1] Fitting Global New Year Effect...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 29464 of 40000, elapsed 0:00:09, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:10, remaining 0:00:00
sampling: iterations 25452 of 80000, elapsed 0:00:08, remaining 0:00:18
sampling: iterations 55982 of 80000, elapsed 0:00:14, remaining 0:00:06
sampling: iterations 76352 of 80000, elapsed 0:00:19, remaining 0:00:01
sampling: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v3.1] Computing DIC...
updating: iterations 22608 of 80000, elapsed 0:00:08, remaining 0:00:20
updating: iterations 42702 of 80000, elapsed 0:00:13, remaining 0:00:11
updating: iterations 62736 of 80000, elapsed 0:00:18, remaining 0:00:05
updating: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v3.1] Computing Gelman-Rubin...
[v3.1] Extracting mu, fitted, and residuals from posterior...
[v3.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.1
[v3.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.1/plots
[v3.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.1
[v3.1] Done.
[v3.2] Fitting Regional New Year Effect...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 27552 of 40000, elapsed 0:00:09, remaining 0:00:04
sampling: iterations 40000 of 40000, elapsed 0:00:09, remaining 0:00:00
sampling: iterations 24096 of 80000, elapsed 0:00:08, remaining 0:00:19
sampling: iterations 53926 of 80000, elapsed 0:00:14, remaining 0:00:07
sampling: iterations 73938 of 80000, elapsed 0:00:19, remaining 0:00:02
sampling: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v3.2] Computing DIC...
updating: iterations 26320 of 80000, elapsed 0:00:09, remaining 0:00:18
updating: iterations 46742 of 80000, elapsed 0:00:14, remaining 0:00:10
updating: iterations 66948 of 80000, elapsed 0:00:19, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:20, remaining 0:00:00
[v3.2] Computing Gelman-Rubin...
[v3.2] Extracting mu, fitted, and residuals from posterior...
[v3.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.2
[v3.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.2/plots
[v3.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.2
[v3.2] Done.
[v3.3] Fitting Mid West Reset Only...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 29318 of 40000, elapsed 0:00:09, remaining 0:00:03
sampling: iterations 40000 of 40000, elapsed 0:00:10, remaining 0:00:00
sampling: iterations 23796 of 80000, elapsed 0:00:08, remaining 0:00:19
sampling: iterations 43484 of 80000, elapsed 0:00:13, remaining 0:00:11
sampling: iterations 63174 of 80000, elapsed 0:00:18, remaining 0:00:05
sampling: iterations 80000 of 80000, elapsed 0:00:21, remaining 0:00:00
[v3.3] Computing DIC...
updating: iterations 24568 of 80000, elapsed 0:00:09, remaining 0:00:20
updating: iterations 62670 of 80000, elapsed 0:00:19, remaining 0:00:05
updating: iterations 80000 of 80000, elapsed 0:00:21, remaining 0:00:00
[v3.3] Computing Gelman-Rubin...
[v3.3] Extracting mu, fitted, and residuals from posterior...
[v3.3] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.3
[v3.3] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.3/plots
[v3.3] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v3.3
[v3.3] Done.
[v4.1] Fitting Regional NY + MW Reset...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 22254 of 40000, elapsed 0:00:09, remaining 0:00:08
sampling: iterations 40000 of 40000, elapsed 0:00:13, remaining 0:00:00
sampling: iterations 18848 of 80000, elapsed 0:00:09, remaining 0:00:29
sampling: iterations 33088 of 80000, elapsed 0:00:14, remaining 0:00:20
sampling: iterations 61716 of 80000, elapsed 0:00:25, remaining 0:00:07
sampling: iterations 80000 of 80000, elapsed 0:00:29, remaining 0:00:00
[v4.1] Computing DIC...
updating: iterations 17908 of 80000, elapsed 0:00:09, remaining 0:00:30
updating: iterations 39206 of 80000, elapsed 0:00:14, remaining 0:00:14
updating: iterations 60508 of 80000, elapsed 0:00:24, remaining 0:00:08
updating: iterations 80000 of 80000, elapsed 0:00:28, remaining 0:00:00
[v4.1] Computing Gelman-Rubin...
[v4.1] Extracting mu, fitted, and residuals from posterior...
[v4.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v4.1
[v4.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v4.1/plots
[v4.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v4.1
[v4.1] Done.
[v5.1] Fitting Hierarchical Intercepts...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 20912 of 40000, elapsed 0:00:09, remaining 0:00:08
sampling: iterations 40000 of 40000, elapsed 0:00:14, remaining 0:00:00
sampling: iterations 19452 of 80000, elapsed 0:00:09, remaining 0:00:29
sampling: iterations 40632 of 80000, elapsed 0:00:15, remaining 0:00:14
sampling: iterations 61882 of 80000, elapsed 0:00:24, remaining 0:00:07
sampling: iterations 80000 of 80000, elapsed 0:00:28, remaining 0:00:00
[v5.1] Computing DIC...
updating: iterations 18598 of 80000, elapsed 0:00:09, remaining 0:00:30
updating: iterations 39198 of 80000, elapsed 0:00:14, remaining 0:00:15
updating: iterations 53110 of 80000, elapsed 0:00:19, remaining 0:00:10
updating: iterations 66940 of 80000, elapsed 0:00:24, remaining 0:00:05
updating: iterations 80000 of 80000, elapsed 0:00:29, remaining 0:00:00
[v5.1] Computing Gelman-Rubin...
[v5.1] Extracting mu, fitted, and residuals from posterior...
[v5.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v5.1
[v5.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v5.1/plots
[v5.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPer10k/v5.1
[v5.1] Done.

=== per-bed ===
[v0.1] Fitting AR(1) Only...
adapting: iterations 4000 of 4000, elapsed 0:00:00, remaining 0:00:00
sampling: iterations 40000 of 40000, elapsed 0:00:04, remaining 0:00:00
sampling: iterations 58112 of 80000, elapsed 0:00:09, remaining 0:00:03
sampling: iterations 80000 of 80000, elapsed 0:00:09, remaining 0:00:00
[v0.1] Computing DIC...
updating: iterations 57304 of 80000, elapsed 0:00:08, remaining 0:00:03
updating: iterations 80000 of 80000, elapsed 0:00:09, remaining 0:00:00
[v0.1] Computing Gelman-Rubin...
[v0.1] Extracting mu, fitted, and residuals from posterior...
[v0.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.1
[v0.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.1/plots
[v0.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.1
[v0.1] Done.
[v0.2] Fitting AR(2) Only...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 11796 of 40000, elapsed 0:00:05, remaining 0:00:12
sampling: iterations 40000 of 40000, elapsed 0:00:09, remaining 0:00:00
sampling: iterations 19836 of 80000, elapsed 0:00:05, remaining 0:00:16
sampling: iterations 41594 of 80000, elapsed 0:00:10, remaining 0:00:09
sampling: iterations 63274 of 80000, elapsed 0:00:15, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:19, remaining 0:00:00
[v0.2] Computing DIC...
updating: iterations 23710 of 80000, elapsed 0:00:08, remaining 0:00:19
updating: iterations 45100 of 80000, elapsed 0:00:13, remaining 0:00:10
updating: iterations 66358 of 80000, elapsed 0:00:18, remaining 0:00:04
updating: iterations 80000 of 80000, elapsed 0:00:19, remaining 0:00:00
[v0.2] Computing Gelman-Rubin...
[v0.2] Extracting mu, fitted, and residuals from posterior...
[v0.2] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.2
[v0.2] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.2/plots
[v0.2] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v0.2
[v0.2] Done.
[v2.1] Fitting AR(1) + Annual Cycle...
adapting: iterations 4000 of 4000, elapsed 0:00:01, remaining 0:00:00
sampling: iterations 32798 of 40000, elapsed 0:00:07, remaining 0:00:02
sampling: iterations 40000 of 40000, elapsed 0:00:07, remaining 0:00:00
sampling: iterations 37022 of 80000, elapsed 0:00:09, remaining 0:00:11
sampling: iterations 63490 of 80000, elapsed 0:00:14, remaining 0:00:04
sampling: iterations 80000 of 80000, elapsed 0:00:16, remaining 0:00:00
[v2.1] Computing DIC...
updating: iterations 29652 of 80000, elapsed 0:00:09, remaining 0:00:15
updating: iterations 73414 of 80000, elapsed 0:00:16, remaining 0:00:01
updating: iterations 80000 of 80000, elapsed 0:00:16, remaining 0:00:00
[v2.1] Computing Gelman-Rubin...
[v2.1] Extracting mu, fitted, and residuals from posterior...
[v2.1] Outputs exported to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.1
[v2.1] Plots saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.1/plots
[v2.1] Significance tests saved to /Users/fluffypony/Library/Mobile Documents/com~apple~CloudDocs/Documents/Galway/PROJECT/CODE/data/models/wide_weekly_scaledPerBed/v2.1
[v2.1] Done.
[v2.2] Fitting 6 Month Cycle Only...

## DIC comparison — per scaling

In [16]:
for scaling, path in DATA_PATHS.items():
    print(f'\n=== DIC table: {scaling} ===')
    try:
        df = compare_dic(path)
        display(df)
    except FileNotFoundError as e:
        print(f'  No results yet: {e}')

=== DIC table: per10k ===

   version               description     deviance    penalty          DIC
0     v4.1    Regional NY + MW Reset  4555.945342  93.596675  4649.542018
1     v5.1   Hierarchical Intercepts  4556.104970  94.158220  4650.263190
2     v3.2  Regional New Year Effect  4604.591347  87.327893  4691.919240
3     v3.1    Global New Year Effect  4682.655557  57.527627  4740.183185
4     v3.3       Mid West Reset Only  5259.243969  57.169625  5316.413594
5     v2.1      AR(1) + Annual Cycle  5294.911046  51.151899  5346.062945
6     v0.2                AR(2) Only  5331.512090  28.621329  5360.133419
7     v2.5    Annual + 2-Month Cycle  5284.875853  75.338452  5360.214305
8     v0.1                AR(1) Only  5344.076309  26.547749  5370.624058
9     v2.4    Annual + 6-Month Cycle  5301.272522  75.803167  5377.075690
10    v2.3        2 Month Cycle Only  5335.263157  50.875960  5386.139117
11    v2.2        6 Month Cycle Only  5349.383457  51.140547  5400.524004

=== DIC table: per-bed ===

   version               description      deviance    penalty           DIC
0     v4.1    Regional NY + MW Reset  11448.892107  93.010592  11541.902699
1     v5.1   Hierarchical Intercepts  11449.124843  93.661447  11542.786289
2     v3.2  Regional New Year Effect  11470.035278  87.312203  11557.347481
3     v3.1    Global New Year Effect  11510.104217  57.206986  11567.311202
4     v3.3       Mid West Reset Only  11738.612170  56.674637  11795.286807
5     v2.1      AR(1) + Annual Cycle  11756.672773  50.978073  11807.650846
6     v2.5    Annual + 2-Month Cycle  11751.828971  75.084209  11826.913181
7     v2.4    Annual + 6-Month Cycle  11773.252000  75.313080  11848.565081
8     v0.1                AR(1) Only  11828.673637  26.609311  11855.282948
9     v0.2                AR(2) Only  11828.277933  28.566858  11856.844791
10    v2.3        2 Month Cycle Only  11823.358221  50.747528  11874.105749
11    v2.2        6 Month Cycle Only  11845.545973  50.894439  11896.440412

=== DIC table: per-budget ===

   version               description      deviance    penalty           DIC
0     v5.1   Hierarchical Intercepts  19858.337693  79.326460  19937.664153
1     v3.1    Global New Year Effect  19920.314654  54.940446  19975.255100
2     v4.1    Regional NY + MW Reset  19899.882216  79.377273  19979.259489
3     v3.2  Regional New Year Effect  19908.341599  77.369883  19985.711481
4     v3.3       Mid West Reset Only  20169.486862  50.389475  20219.876337
5     v2.1      AR(1) + Annual Cycle  20176.010662  48.582501  20224.593163
6     v2.5    Annual + 2-Month Cycle  20171.444711  72.073717  20243.518428
7     v2.4    Annual + 6-Month Cycle  20195.392089  70.605745  20265.997834
8     v0.1                AR(1) Only  20253.893406  27.000602  20280.894009
9     v0.2                AR(2) Only  20253.948705  29.293102  20283.241807
10    v2.3        2 Month Cycle Only  20248.912325  50.633343  20299.545668
11    v2.2        6 Month Cycle Only  20274.192723  48.780630  20322.973353

## Alpha (baseline intercept) — per scaling

In [17]:
from pathlib import Path
import numpy as np

def _alpha_table(data_path, versions=None):
    stem = Path(data_path).stem
    scale_dir = Path('data/models') / stem
    if not scale_dir.exists():
        raise FileNotFoundError(f'No output for {stem}')
    frames = []
    for samples_path in sorted(scale_dir.glob('*/raw_samples.csv')):
        version = samples_path.parent.name
        if versions is not None and version not in versions:
            continue
        fitted_path = samples_path.parent / 'fitted.csv'
        if not fitted_path.exists():
            continue
        regions = list(pd.read_csv(fitted_path).columns)
        df = pd.read_csv(samples_path)
        alpha_cols = [c for c in df.columns if c.startswith('alpha[')]
        if not alpha_cols:
            continue
        rows = []
        for i, col in enumerate(sorted(alpha_cols, key=lambda x: int(x.strip('alpha[]')))):
            region = regions[i] if i < len(regions) else col
            s = df[col]
            rows.append({'Region': region,
                         'Mean': round(s.mean(), 4),
                         'SD': round(s.std(), 4),
                         '2.5%': round(np.percentile(s, 2.5), 4),
                         '97.5%': round(np.percentile(s, 97.5), 4)})
        tbl = pd.DataFrame(rows).set_index('Region')
        tbl.name = version
        frames.append((version, tbl))
    return frames

for scaling, path in DATA_PATHS.items():
    print(f'\n=== Alpha table: {scaling} ===')
    try:
        for version, tbl in _alpha_table(path, versions=['v4.1']):
            print(f'  -- {version}')
            display(tbl)
    except FileNotFoundError as e:
        print(f'  No results yet: {e}')

=== Alpha table: per10k ===
  -- v5.1

                             Mean      SD    2.5%   97.5%
Region
HSE Dublin and Midlands    3.9988  0.1926  3.6208  4.3779
HSE Dublin and North East  2.2978  0.1325  2.0368  2.5582
HSE Dublin and South East  3.0025  0.1469  2.7121  3.2926
HSE Mid West               8.1819  0.3069  7.5738  8.7776
HSE South West             4.4233  0.2440  3.9446  4.9029
HSE West and North West    6.3393  0.2656  5.8182  6.8611

=== Alpha table: per-bed ===
  -- v5.1

                              Mean      SD     2.5%    97.5%
Region
HSE Dublin and Midlands    16.1180  0.7780  14.6055  17.6504
HSE Dublin and North East   9.3783  0.5318   8.3445  10.4388
HSE Dublin and South East  12.8108  0.6307  11.5828  14.0662
HSE Mid West               37.2293  1.5106  34.2407  40.1738
HSE South West             21.2022  1.1340  18.9911  23.4393
HSE West and North West    25.8604  1.0859  23.7246  27.9997

=== Alpha table: per-budget ===
  -- v5.1

                               Mean       SD      2.5%     97.5%
Region
HSE Dublin and Midlands    113.2785   5.5850  102.3039  124.2708
HSE Dublin and North East   77.8051   4.4935   69.0324   86.6994
HSE Dublin and South East  109.3564   5.5007   98.6646  120.3588
HSE Mid West               276.8639  11.7510  253.6583  299.8206
HSE South West             167.0963   9.1601  149.0968  185.1110
HSE West and North West    194.8059   8.3749  178.4074  211.2855

## Ranks (alpha posterior ranks) — per scaling

In [18]:
def _ranks_table(data_path, versions=None):
    stem = Path(data_path).stem
    scale_dir = Path('data/models') / stem
    if not scale_dir.exists():
        raise FileNotFoundError(f'No output for {stem}')
    frames = []
    for ranks_path in sorted(scale_dir.glob('*/ranks.csv')):
        version = ranks_path.parent.name
        if versions is not None and version not in versions:
            continue
        df = pd.read_csv(ranks_path, index_col=0)
        df.index.name = 'Region'
        df = df.rename(columns={'50%': 'Median'}).sort_values('ranked_mean')
        frames.append((version, df))
    return frames

for scaling, path in DATA_PATHS.items():
    print(f'\n=== Ranks table: {scaling} ===')
    try:
        for version, tbl in _ranks_table(path, versions=['v4.1']):
            print(f'  -- {version}')
            display(tbl)
    except FileNotFoundError as e:
        print(f'  No results yet: {e}')

=== Ranks table: per10k ===
  -- v5.1

                               mean       std  25%  Median  75%  ranked_mean
Region
HSE Dublin and North East  1.000375  0.019361  1.0     1.0  1.0          1.0
HSE Dublin and South East  1.999662  0.020307  2.0     2.0  2.0          2.0
HSE Dublin and Midlands    3.085488  0.279742  3.0     3.0  3.0          3.0
HSE South West             3.914475  0.279663  4.0     4.0  4.0          4.0
HSE West and North West    5.000038  0.006124  5.0     5.0  5.0          5.0
HSE Mid West               5.999962  0.006124  6.0     6.0  6.0          6.0

=== Ranks table: per-bed ===
  -- v5.1

                               mean       std  25%  Median  75%  ranked_mean
Region
HSE Dublin and North East  1.000050  0.007071  1.0     1.0  1.0          1.0
HSE Dublin and South East  2.000662  0.027606  2.0     2.0  2.0          2.0
HSE Dublin and Midlands    2.999425  0.029149  3.0     3.0  3.0          3.0
HSE South West             4.001787  0.045380  4.0     4.0  4.0          4.0
HSE West and North West    4.998075  0.043833  5.0     5.0  5.0          5.0
HSE Mid West               6.000000  0.000000  6.0     6.0  6.0          6.0

=== Ranks table: per-budget ===
  -- v5.1

                               mean       std  25%  Median  75%  ranked_mean
Region
HSE Dublin and North East  1.000012  0.003536  1.0     1.0  1.0          1.0
HSE Dublin and South East  2.305400  0.460607  2.0     2.0  3.0          2.0
HSE Dublin and Midlands    2.694587  0.460585  2.0     3.0  3.0          3.0
HSE South West             4.012512  0.111158  4.0     4.0  4.0          4.0
HSE West and North West    4.987488  0.111158  5.0     5.0  5.0          5.0
HSE Mid West               6.000000  0.000000  6.0     6.0  6.0          6.0

## Phi (AR(1) coefficient) — per scaling

In [19]:
def _phi_table(data_path, versions=None):
    stem = Path(data_path).stem
    scale_dir = Path('data/models') / stem
    if not scale_dir.exists():
        raise FileNotFoundError(f'No output for {stem}')
    rows = []
    for gp_path in sorted(scale_dir.glob('*/global_parameters.csv')):
        version = gp_path.parent.name
        if versions is not None and version not in versions:
            continue
        df = pd.read_csv(gp_path)
        phi_rows = df[df['Parameter'].str.startswith('phi')]
        if phi_rows.empty:
            continue
        for _, row in phi_rows.iterrows():
            rows.append({'version': version, **row.to_dict()})
    if not rows:
        raise ValueError(f'No phi parameters found under {scale_dir}')
    return pd.DataFrame(rows).sort_values(['version', 'Parameter']).reset_index(drop=True)

for scaling, path in DATA_PATHS.items():
    print(f'\n=== Phi table: {scaling} ===')
    try:
        display(_phi_table(path, versions=['v4.1']))
    except (FileNotFoundError, ValueError) as e:
        print(f'  No results yet: {e}')

=== Phi table: per10k ===

  version Parameter    Mean      SD    2.5%   97.5%
0    v5.1       phi  0.6604  0.0284  0.6053  0.7164

=== Phi table: per-bed ===

  version Parameter    Mean      SD    2.5%   97.5%
0    v5.1       phi  0.6481  0.0276  0.5947  0.7024

=== Phi table: per-budget ===

  version Parameter    Mean      SD    2.5%   97.5%
0    v5.1       phi  0.6551  0.0265  0.6033  0.7078

## Sync plots → dashboard assets

In [ ]:
import shutil
from pathlib import Path

_SCALE_MAP = {
    "per10k":     "wide_weekly_scaledPer10k",
    "per_bed":    "wide_weekly_scaledPerBed",
    "per_budget": "wide_weekly_scaledPerBudgetThousands",
}
_DASHBOARD_PLOTS = [
    "mu_fit.png",
    "fitted.png",
    "residuals_combined.png",
    "residuals_ts.png",
    "residuals_vs_fitted.png",
]

_project = Path(".")
_updated = 0
_skipped = 0

for scale_key, stem in _SCALE_MAP.items():
    data_base  = _project / "data" / "models" / stem
    asset_base = _project / "dashboard" / "assets" / "models" / scale_key

    if not data_base.exists():
        print(f"  [skip] no data dir for {scale_key}")
        continue

    for version_dir in sorted(data_base.iterdir()):
        if not version_dir.is_dir():
            continue
        plots_dir = version_dir / "plots"
        asset_dir = asset_base / version_dir.name
        if not plots_dir.is_dir() or not asset_dir.is_dir():
            continue

        for fname in _DASHBOARD_PLOTS:
            src = plots_dir / fname
            dst = asset_dir / fname
            if not src.exists():
                continue
            if not dst.exists() or src.stat().st_mtime > dst.stat().st_mtime:
                shutil.copy2(src, dst)
                print(f"  updated  {scale_key}/{version_dir.name}/{fname}")
                _updated += 1
            else:
                _skipped += 1

print(f"\nDone — updated: {_updated}  |  already current: {_skipped}")